### PR TITLE
update version to 1.3.6

### PR DESCRIPTION
**Pull request by Stevierene82**
Updating to version 1.3.6, including windows build

### CODE REVIEW

**Comment by bgruening** [comment]
@conda-forge-admin, please rerender

**Comment by Stevierene82** [comment]
@bgruening. So, the error this is running into is that it can't find the ttf2pt1.c file:
image

It looks like what we need can be found here: https://github.com/wch/Rttf2pt1 in the src folder, but I'm not sure what the proper way is to go about using this. Any insight would be appreciated. Thanks!

**Comment by bgruening** [comment]
I understand the error in the way that gcc.exe is missing.

**Comment by Stevierene82** [comment]
oh, i completely misread that. is that something I can fix on my end? (thanks for the help! i'm still new at this!)

**Comment by bgruening** [comment]
@conda-forge-admin, please rerender

**Pull request closed without merging**
